# Generated by Django 3.1.4 on 2021-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0002_auto_20210226_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ManyToManyField(to='exercises_app.Category'),
        ),
    ]
